version: '3.8'

volumes:
  pg_post:

services:
  post_redis:
    image: redis:latest
    container_name: post_redis
    ports:
      - "127.0.0.1:6379:6379"

  post_front:
    container_name: post_front
    build: ./front
    ports:
      - '3000:3000'
    depends_on:
      - post_backend

  post_backend:
    container_name: post_backend
    build:
      context: ./Postbin
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      post_postgresdb:
        condition: service_healthy

  post_postgresdb:
    container_name: post_postgresdb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postbin
      POSTGRES_USER: post_user
      POSTGRES_PASSWORD: post_db
    volumes:
      - pg_post:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "post_user", "-d", "postbin"]
      interval: 10s
      timeout: 5s
      retries: 3
