version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - REDIS_USER=${REDIS_USER}
#      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
  front:
    build: ./front
    ports:
      - '8084:8084'
    depends_on:
      - back
  backend:
    container_name: backend
    build:
      context: ./Postbin
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: javaschema
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
    ports:
      - '8080:8080'
    depends_on:
      postgresdb:
        condition: service_healthy
  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    environment:
      POSTGRES_DB: postbin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
